apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: moodle
  namespace: dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: moodle
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: moodle
        minAllowed:
          cpu: "250m"
          memory: "512Mi"
        maxAllowed:
          cpu: "1500m"
          memory: "2Gi"
        controlledResources:
          - "cpu"
          - "memory"