# PV Moodle

apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-pv 
  labels:
    type: nfs
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle-project
    app.kubernetes.io/instance: n7
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /volume1/nfs/k8s-data/moodle/moodle
    server: 192.168.1.20 


# PVC Moodle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pvc
  namespace: dev
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle-project
    app.kubernetes.io/instance: n7
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
  volumeName: moodle-pv

# StatefulSet Moodle
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moodle
  namespace: dev
spec:
  replicas: 1
  serviceName: moodle
  selector:
    matchLabels:
        app.kubernetes.io/name: moodle
        app.kubernetes.io/part-of: moodle-project
        app.kubernetes.io/instance: n7
  revisionHistoryLimit: 15
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: moodle
        app.kubernetes.io/part-of: moodle-project
        app.kubernetes.io/instance: n7
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 1029
        runAsGroup: 100
        fsGroup: 100
      containers:
      - name: moodle
        image: bitnamilegacy/moodle@sha256:a7bd6bf34b736dad22ee22168d4bfd830b7bedf9e34b89732d92d437317cb1d0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: moodle-config
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - name: moodle-storage
          mountPath: /bitnami/moodle
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /
            port: 8443
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /opt/bitnami/php/bin/php
              - -v
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: moodle-storage
        persistentVolumeClaim:
          claimName: moodle-pvc

# Service Moodle
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: dev
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle-project
    app.kubernetes.io/instance: n7
spec:
  type: NodePort
  ports:
  - name: https
    port: 8443
    targetPort: 8443
    nodePort: 30003
  selector:
    app.kubernetes.io/name: moodle
