apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-pv 
  labels:
    type: nfs
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle-project
    app.kubernetes.io/instance: n7
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /volume1/nfs/k8s-data/moodle/moodle
    server: 192.168.1.20 