apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moodle
  namespace: dev
spec:
  replicas: 1
  serviceName: moodle
  selector:
    matchLabels:
        app.kubernetes.io/name: moodle
        app.kubernetes.io/part-of: moodle-project
        app.kubernetes.io/instance: n7
  revisionHistoryLimit: 15
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: moodle
        app.kubernetes.io/part-of: moodle-project
        app.kubernetes.io/instance: n7
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      # serviceAccountName: moodle-sa
      # automountServiceAccountToken: false
      containers:
      - name: moodle
        image: bitnamilegacy/moodle@sha256:a7bd6bf34b736dad22ee22168d4bfd830b7bedf9e34b89732d92d437317cb1d0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: moodle-config
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          # capabilities:
          #   drop:
          #     - ALL
          #   add:
          #     - CHOWN
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - name: moodle-storage
          mountPath: /bitnami/moodle
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /
            port: 8443
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /opt/bitnami/php/bin/php
              - -v
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
      volumes:
      - name: moodle-storage
        persistentVolumeClaim:
          claimName: moodle-pvc
