apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: dev
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle-project
    app.kubernetes.io/instance: n7
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.80
  ports:
  - name: https
    port: 8443
    targetPort: 8443
    nodePort: 30003
  selector:
    app.kubernetes.io/name: moodle
