apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  namespace: books
spec:
  type: NodePort
  selector:
    app: calibre-web
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    nodePort: 30010
