# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguardhome-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /volume1/nfs/k8s-data/adguardhome 
    server: 192.168.1.20
---
# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
  volumeName: adguardhome-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguardhome
  template:
    metadata:
      labels:
        app: adguardhome
    spec:
      containers:
        - name: adguardhome
          image: adguard/adguardhome:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 67
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 443
              protocol: UDP
            - containerPort: 3000
              protocol: TCP
            - containerPort: 853
              protocol: TCP
            - containerPort: 784
              protocol: UDP
            - containerPort: 853
              protocol: UDP
            - containerPort: 8853
              protocol: UDP
            - containerPort: 5443
              protocol: TCP
            - containerPort: 5443
              protocol: UDP
          volumeMounts:
            - name: adguard-storage
              mountPath: /opt/adguardhome/work
              subPath: work
            - name: adguard-storage
              mountPath: /opt/adguardhome/conf
              subPath: conf
      volumes:
        - name: adguard-storage
          persistentVolumeClaim:
            claimName: adguardhome-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: adguardhome-service
  namespace: prod
spec:
  selector:
    app: adguardhome
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dhcp-udp
      port: 67
      targetPort: 67
      protocol: UDP
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30005
      protocol: TCP
    - name: https-tcp
      port: 443
      targetPort: 443
      protocol: TCP
    - name: https-udp
      port: 443
      targetPort: 443
      protocol: UDP
    - name: ui
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: dns-over-tls
      port: 853
      targetPort: 853
      protocol: TCP
    - name: dns-quic
      port: 784
      targetPort: 784
      protocol: UDP
    - name: dns-over-udp
      port: 853
      targetPort: 853
      protocol: UDP
    - name: dns-alt-udp
      port: 8853
      targetPort: 8853
      protocol: UDP
    - name: dns-alt-tcp
      port: 5443
      targetPort: 5443
      protocol: TCP
    - name: dns-alt2-udp
      port: 5443
      targetPort: 5443
      protocol: UDP
  type: NodePort